services:
  focus-app:
    build:
      context: .
    container_name: "focus"
    ports:
      - "3532:3532"
    environment:
      - "NODE_ENV=production"
    volumes:
      - "./data:/usr/src/app/server/data"
