services:
  app:
    container_name: "focus"
    image: "focus:latest"
    build:
      context: .
    ports:
      - "3532:3532"
    environment:
      - "NODE_ENV=production"
    volumes:
      - "focus_data:/usr/src/app/server/data"
    restart: "unless-stopped"

volumes:
  focus_data:
